### ISSUE TITLE
Replication with "--progress" option failed with an error message of "Error: Cannot read property 'progress' of undefined".

### ISSUE THREAD

**Issue by keisuke-kanao** [orbitdb/orbit-db-cli#18]
When I invoked: 
<pre>
orbitdb replicate address --progress
</pre>
The command failed with an error message of "Error: Cannot read property 'progress' of undefined".
In my case, this issue was fixed by replacing "db._replicationInfo" with "db._replicationStatus" in orbit-db-cli/src/lib/replication-loop.js.

**Comment by haadcode** [comment]
This should be fixed now in the latest version (v0.0.16). If you still experience errors, let us know!
